export const colleges = [
  {
    "name": "Indian Institute of Technology Delhi",
    "slug": "indian-institute-of-technology-delhi",
    "location": "Delhi",
    "state": "Delhi",
    "fees": 250000,
    "rating": 4.9,
    "placements": 34.5,
    "highestPackage": 260.0,
    "averagePackage": 30.2,
    "image": "/colleges/iit-delhi.jpg",
    "description": "Indian Institute of Technology Delhi delivers strong placements, advanced research, innovation opportunities, industry collaboration, entrepreneurship support, and academic excellence through modern labs and a highly competitive engineering ecosystem.",
    "established": 1961,
    "ownership": "Government",
    "nirfRanking": 2,
    "campusSize": 320,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Bombay",
    "slug": "indian-institute-of-technology-bombay",
    "location": "Mumbai",
    "state": "Maharashtra",
    "fees": 230000,
    "rating": 4.9,
    "placements": 35.0,
    "highestPackage": 300.0,
    "averagePackage": 32.1,
    "image": "/colleges/iit-bombay.jpg",
    "description": "Indian Institute of Technology Bombay is recognized for top placements, impactful research, innovation-led learning, strong industry collaboration, entrepreneurship culture, and academic excellence across premier engineering disciplines.",
    "established": 1958,
    "ownership": "Government",
    "nirfRanking": 3,
    "campusSize": 550,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Aerospace Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Madras",
    "slug": "indian-institute-of-technology-madras",
    "location": "Chennai",
    "state": "Tamil Nadu",
    "fees": 220000,
    "rating": 4.9,
    "placements": 34.2,
    "highestPackage": 250.0,
    "averagePackage": 29.8,
    "image": "/colleges/iit-madras.jpg",
    "description": "Indian Institute of Technology Madras combines excellent placements, world-class research, innovation ecosystems, industry collaboration, entrepreneurship incubation, and academic excellence in a dynamic engineering environment.",
    "established": 1959,
    "ownership": "Government",
    "nirfRanking": 1,
    "campusSize": 617,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  },
  {
    "name": "Indian Institute of Technology Kanpur",
    "slug": "indian-institute-of-technology-kanpur",
    "location": "Kanpur",
    "state": "Uttar Pradesh",
    "fees": 220000,
    "rating": 4.8,
    "placements": 32.8,
    "highestPackage": 190.0,
    "averagePackage": 27.4,
    "image": "/colleges/iit-kanpur.jpg",
    "description": "Indian Institute of Technology Kanpur offers outstanding placements, research intensity, innovation-driven academics, deep industry collaboration, entrepreneurship support, and academic excellence for high-performing engineering students.",
    "established": 1959,
    "ownership": "Government",
    "nirfRanking": 4,
    "campusSize": 1050,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Aerospace Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Kharagpur",
    "slug": "indian-institute-of-technology-kharagpur",
    "location": "Kharagpur",
    "state": "West Bengal",
    "fees": 210000,
    "rating": 4.8,
    "placements": 31.5,
    "highestPackage": 200.0,
    "averagePackage": 25.8,
    "image": "/colleges/iit-kharagpur.jpg",
    "description": "Indian Institute of Technology Kharagpur stands out for strong placements, interdisciplinary research, innovation culture, industry collaboration, entrepreneurship opportunities, and academic excellence across diverse engineering programs.",
    "established": 1951,
    "ownership": "Government",
    "nirfRanking": 6,
    "campusSize": 1180,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  },
  {
    "name": "Indian Institute of Technology Guwahati",
    "slug": "indian-institute-of-technology-guwahati",
    "location": "Guwahati",
    "state": "Assam",
    "fees": 210000,
    "rating": 4.7,
    "placements": 28.6,
    "highestPackage": 160.0,
    "averagePackage": 22.9,
    "image": "/colleges/iit-guwahati.jpg",
    "description": "Indian Institute of Technology Guwahati provides impressive placements, research-led learning, innovation-focused education, strong industry collaboration, entrepreneurship mentoring, and academic excellence in core and emerging technologies.",
    "established": 1994,
    "ownership": "Government",
    "nirfRanking": 7,
    "campusSize": 700,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  },
  {
    "name": "Indian Institute of Technology Hyderabad",
    "slug": "indian-institute-of-technology-hyderabad",
    "location": "Hyderabad",
    "state": "Telangana",
    "fees": 235000,
    "rating": 4.8,
    "placements": 30.2,
    "highestPackage": 175.0,
    "averagePackage": 24.8,
    "image": "/colleges/iit-hyderabad.jpg",
    "description": "Indian Institute of Technology Hyderabad is known for high placements, advanced research, innovation-led curriculum, strong industry collaboration, entrepreneurship support, and academic excellence in next-generation engineering domains.",
    "established": 2008,
    "ownership": "Government",
    "nirfRanking": 8,
    "campusSize": 576,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  },
  {
    "name": "Indian Institute of Technology Indore",
    "slug": "indian-institute-of-technology-indore",
    "location": "Indore",
    "state": "Madhya Pradesh",
    "fees": 225000,
    "rating": 4.7,
    "placements": 24.5,
    "highestPackage": 120.0,
    "averagePackage": 19.2,
    "image": "/colleges/iit-indore.jpg",
    "description": "Indian Institute of Technology Indore offers strong placements, research excellence, innovation-oriented academics, industry collaboration, entrepreneurship development, and a rigorous learning environment for engineering aspirants.",
    "established": 2009,
    "ownership": "Government",
    "nirfRanking": 16,
    "campusSize": 510,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology BHU Varanasi",
    "slug": "indian-institute-of-technology-bhu-varanasi",
    "location": "Varanasi",
    "state": "Uttar Pradesh",
    "fees": 205000,
    "rating": 4.7,
    "placements": 24.0,
    "highestPackage": 115.0,
    "averagePackage": 18.8,
    "image": "/colleges/iit-bhu-varanasi.jpg",
    "description": "Indian Institute of Technology BHU Varanasi blends strong placements, applied research, innovation culture, industry collaboration, entrepreneurship initiatives, and academic excellence within a respected engineering heritage.",
    "established": 1919,
    "ownership": "Government",
    "nirfRanking": 15,
    "campusSize": 400,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  },
  {
    "name": "Indian Institute of Technology Ropar",
    "slug": "indian-institute-of-technology-ropar",
    "location": "Rupnagar",
    "state": "Punjab",
    "fees": 205000,
    "rating": 4.6,
    "placements": 21.8,
    "highestPackage": 105.0,
    "averagePackage": 17.8,
    "image": "/colleges/iit-ropar.jpg",
    "description": "Indian Institute of Technology Ropar emphasizes strong placements, quality research, innovation-driven programs, industry collaboration, entrepreneurship opportunities, and academic excellence across engineering specializations.",
    "established": 2008,
    "ownership": "Government",
    "nirfRanking": 22,
    "campusSize": 500,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Gandhinagar",
    "slug": "indian-institute-of-technology-gandhinagar",
    "location": "Gandhinagar",
    "state": "Gujarat",
    "fees": 205000,
    "rating": 4.6,
    "placements": 20.5,
    "highestPackage": 98.0,
    "averagePackage": 16.2,
    "image": "/colleges/iit-gandhinagar.jpg",
    "description": "Indian Institute of Technology Gandhinagar features good placements, vibrant research, innovation-focused education, industry collaboration, entrepreneurship pathways, and academic excellence in a modern engineering setting.",
    "established": 2008,
    "ownership": "Government",
    "nirfRanking": 18,
    "campusSize": 400,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Jodhpur",
    "slug": "indian-institute-of-technology-jodhpur",
    "location": "Jodhpur",
    "state": "Rajasthan",
    "fees": 200000,
    "rating": 4.5,
    "placements": 19.8,
    "highestPackage": 90.0,
    "averagePackage": 15.6,
    "image": "/colleges/iit-jodhpur.jpg",
    "description": "Indian Institute of Technology Jodhpur supports notable placements, meaningful research, innovation-led education, strong industry collaboration, entrepreneurship culture, and academic excellence for aspiring engineers.",
    "established": 2008,
    "ownership": "Government",
    "nirfRanking": 28,
    "campusSize": 852,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  },
  {
    "name": "Indian Institute of Technology Bhubaneswar",
    "slug": "indian-institute-of-technology-bhubaneswar",
    "location": "Bhubaneswar",
    "state": "Odisha",
    "fees": 195000,
    "rating": 4.5,
    "placements": 18.9,
    "highestPackage": 85.0,
    "averagePackage": 14.9,
    "image": "/colleges/iit-bhubaneswar.jpg",
    "description": "Indian Institute of Technology Bhubaneswar offers solid placements, research-active departments, innovation-led academics, industry collaboration, entrepreneurship support, and academic excellence across engineering streams.",
    "established": 2008,
    "ownership": "Government",
    "nirfRanking": 54,
    "campusSize": 936,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Patna",
    "slug": "indian-institute-of-technology-patna",
    "location": "Patna",
    "state": "Bihar",
    "fees": 195000,
    "rating": 4.6,
    "placements": 20.2,
    "highestPackage": 92.0,
    "averagePackage": 15.9,
    "image": "/colleges/iit-patna.jpg",
    "description": "Indian Institute of Technology Patna combines reliable placements, research excellence, innovation-driven education, industry collaboration, entrepreneurship support, and academic excellence in a contemporary campus ecosystem.",
    "established": 2008,
    "ownership": "Government",
    "nirfRanking": 34,
    "campusSize": 501,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Tirupati",
    "slug": "indian-institute-of-technology-tirupati",
    "location": "Tirupati",
    "state": "Andhra Pradesh",
    "fees": 190000,
    "rating": 4.5,
    "placements": 17.6,
    "highestPackage": 72.0,
    "averagePackage": 13.8,
    "image": "/colleges/iit-tirupati.jpg",
    "description": "Indian Institute of Technology Tirupati fosters stable placements, quality research, innovation-led academics, productive industry collaboration, entrepreneurship guidance, and academic excellence across engineering disciplines.",
    "established": 2015,
    "ownership": "Government",
    "nirfRanking": 61,
    "campusSize": 548,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Palakkad",
    "slug": "indian-institute-of-technology-palakkad",
    "location": "Palakkad",
    "state": "Kerala",
    "fees": 185000,
    "rating": 4.5,
    "placements": 16.5,
    "highestPackage": 68.0,
    "averagePackage": 12.9,
    "image": "/colleges/iit-palakkad.jpg",
    "description": "Indian Institute of Technology Palakkad delivers good placements, active research, innovation culture, industry collaboration, entrepreneurship mentoring, and academic excellence with a strong foundation in engineering education.",
    "established": 2015,
    "ownership": "Government",
    "nirfRanking": 64,
    "campusSize": 504,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "Indian Institute of Technology Dharwad",
    "slug": "indian-institute-of-technology-dharwad",
    "location": "Dharwad",
    "state": "Karnataka",
    "fees": 180000,
    "rating": 4.4,
    "placements": 15.8,
    "highestPackage": 65.0,
    "averagePackage": 12.4,
    "image": "/colleges/iit-dharwad.jpg",
    "description": "Indian Institute of Technology Dharwad promotes growing placements, meaningful research, innovation-centric learning, industry collaboration, entrepreneurship development, and academic excellence across engineering programs.",
    "established": 2016,
    "ownership": "Government",
    "nirfRanking": 93,
    "campusSize": 470,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "National Institute of Technology Tiruchirappalli",
    "slug": "national-institute-of-technology-tiruchirappalli",
    "location": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "fees": 165000,
    "rating": 4.7,
    "placements": 24.0,
    "highestPackage": 70.0,
    "averagePackage": 16.8,
    "image": "/colleges/nit-trichy.jpg",
    "description": "National Institute of Technology Tiruchirappalli is known for excellent placements, research depth, innovation-focused curriculum, industry collaboration, entrepreneurship initiatives, and academic excellence in engineering education.",
    "established": 1964,
    "ownership": "Government",
    "nirfRanking": 9,
    "campusSize": 800,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Information Technology",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "National Institute of Technology Karnataka Surathkal",
    "slug": "national-institute-of-technology-karnataka-surathkal",
    "location": "Mangaluru",
    "state": "Karnataka",
    "fees": 160000,
    "rating": 4.7,
    "placements": 22.8,
    "highestPackage": 65.0,
    "averagePackage": 15.9,
    "image": "/colleges/nit-surathkal.jpg",
    "description": "National Institute of Technology Karnataka Surathkal delivers strong placements, respected research, innovation-oriented academics, industry collaboration, entrepreneurship support, and academic excellence on a well-established campus.",
    "established": 1960,
    "ownership": "Government",
    "nirfRanking": 12,
    "campusSize": 295,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Information Technology",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering"
    ]
  },
  {
    "name": "National Institute of Technology Rourkela",
    "slug": "national-institute-of-technology-rourkela",
    "location": "Rourkela",
    "state": "Odisha",
    "fees": 155000,
    "rating": 4.6,
    "placements": 20.5,
    "highestPackage": 58.0,
    "averagePackage": 14.4,
    "image": "/colleges/nit-rourkela.jpg",
    "description": "National Institute of Technology Rourkela provides strong placements, quality research, innovation-driven learning, active industry collaboration, entrepreneurship opportunities, and academic excellence across major engineering branches.",
    "established": 1961,
    "ownership": "Government",
    "nirfRanking": 19,
    "campusSize": 647,
    "courses": [
      "Computer Science",
      "AI & ML",
      "Data Science",
      "Information Technology",
      "Electronics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Biotechnology"
    ]
  }
];
